config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cities#index'

  resources :cities   do
    resources :printers
  end 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/printer.rb
class Printer < ActiveRecord::Base
	has_one :city
	belongs_to :city
	validates :number, uniqueness: true
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cities/:city_id/printers
  def index
    @printers = Printer.where(city_id: params[:city_id])
  end

 # GET /cities/:city_id/printers/:id
  def show
  end

  # GET /cities/:city_id/printers/new
  def new
    @printer = Printer.new
  end

  # GET /cities/:city_id/printers/:id/edit
  def edit
  end

  # POST /cities/:city_id/printers
  def create
    # TODO get classes working
    # TODO move phone_numbers into its own worker
    # TODO move the phone_number.each logic into a sidekiq worker

    YelpWorker.perform_async(params[:city_id])

    redirect_to :root
  end

  # PUT /cities/:city_id/printers/:id
  def update
    
  end

  # DELETE /cities/:city_id/printers/:id
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: 'Printer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.fetch(:printer, {})
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/printers/_form.html.erb
<%= form_tag(controller: "printers", action: "create", method: "post") do %>
	<%= submit_tag("Search") %>
<% end %>

app/views/printers/edit.html.erb
<h1>Editing Printer</h1>

<%= render 'form' %>

<%= link_to 'Show', @printer %> |
<%= link_to 'Back', printers_path %>

app/views/printers/index.html.erb
<h1><%=@printers.last.city.name %></h1>
<h3>Listing Printers</h3>
<%=link_to 'Cities Index', cities_path, class: "btn btn-primary"%>



<div class= "container">

  <table class= "table table-striped">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>City ID</th>
        <th>Company</th>
        <th>Phone Number</th>
        <th>Address</th>
        <th>Rating</th>
      </tr>
    </thead>

    <tbody>
      <% @printers.each do |printer| %>
        <tr>

          <td><%= link_to 'Show', city_printer_path(:city_id, :id) %></td>

          <td><%= link_to 'Edit', edit_city_printer_path(printer, :id) %></td>

          <td><%= link_to 'Destroy', city_printers_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%=printer.city_id%></td>
          <td><%=printer.company%></td>
          <td><%=printer.number%></td>
          <td><%=printer.address%></td>
          <td><%=printer.rating%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<br>

<%#= link_to 'New Printer', new_printer_path %>

app/views/printers/new.html.erb
<h1>New Printer</h1>

<%= render 'form' %>

app/views/printers/show.html.erb
<%= link_to 'Edit', edit_printer_path(@printer) %>
<%= link_to 'Back', printers_path %>