config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cities#index'

  resources :cities   do
    resources :printers
  end 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :printers
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "City Name" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Austin Tx", required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>
<!-- <header> devise </header> -->

<table class= "table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <th>City</th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <tbody>
    <% @cities.each do |city| %>
      
      <tr>  
        <td><%= city.name %> </td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "City Printers Index", city_printers_path(city_id: city.id)%> </td>
        <td><%= link_to "Create New Printer List", new_city_printer_path(city_id: city.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>

<%= link_to 'New City', new_city_path %>
  

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<h1><%=@city.name%></h1>
<h4> Show Page </h4>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back to all cities', cities_path %>